import { Paper } from '@mui/material';
import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react';
import PropInput from '../components/PropInput';
import TruthTable from '../components/TruthTable';
import styles from '../styles/Home.module.css'


export default function Home() {
  const [screenWidth, setScreenWidth] = useState(null);
  const [propositionResult, setPropositionResult] = useState([]);

  const [showTable, setShowTable] = useState(false);
  let hasWindow = typeof window !== "undefined";
  
  useEffect(() => {
    const handleResize = () => {
      setScreenWidth(window.innerWidth);
      
    }
    if (hasWindow) {
      setScreenWidth(window.innerWidth);
      window.addEventListener("resize", handleResize);
    }
    return () => window.removeEventListener("resize", handleResize);
  }, [hasWindow])

  // useEffect(() => {
  //   setShowTable(propositionResult.length > 0);
  // }, [propositionResult])


  const getPropositionResult = (result) => {
    setPropositionResult(result);
  }

  if (propositionResult.length) {
    let [map, arr] = propositionResult;
    // console.log(map);
    // console.log(arr);
  }

  
  
  return (
    <div className={`border border-solid flex justify-center ${screenWidth > 720 ? 'p-20' : screenWidth > 300 && 'p-8'}`}>
      <Head>
        <title>Discrete - little helper</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
      <div className="border border-solid border-gray-400 flex-1 rounded-md">
        <h1 className="text-gray-700 text-center my-2 text-2xl">Truth Table Generator</h1>
        <hr className='border-blue-400 mx-6' />
        <PropInput getPropositionResult={getPropositionResult} />
        {propositionResult.length > 0 ? <TruthTable tableResult={propositionResult} /> : null }
      </div>
      
      
      
    </div>
  )
}
